name 'algo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures algo'
version '0.2.1'
chef_version '>= 16.0'
# issues_url 'https://github.com/<insert_org_here>/algo/issues'
# source_url 'https://github.com/<insert_org_here>/algo'

depends 'apt', '~> 7.3.0'
depends 'apparmor', '~> 3.1.0'
depends 'iptables', '~> 7.1.0'

gem 'ipaddress'
gem 'x25519'
gem 'base64'
